src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Best Seller</fullName>
                </value>
                <value>
                    <fullName>Exclusive</fullName>
                </value>
                <value>
                    <fullName>Newcoming</fullName>
                </value>
                <value>
                    <fullName>Economical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Clothes</fullName>
                </value>
                <value>
                    <fullName>Cars</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemsControllerTest.cls
@IsTest
private class ItemsControllerTest {

	@IsTest
	static void testGetAllItems() {
		Item__c testItem = new Item__c();
		testItem.Name = 'Banana';
		testItem.Type__c = 'Food';
		testItem.Family__c = 'Best Seller';
		testItem.Description__c = 'A yellow fruit';
		insert testItem;

		Test.startTest();
		List<Item__c> foods = ItemsController.getAllItems('Food', '', '', 0);
		List<Item__c> searchResults = ItemsController.getAllItems('', '', 'Banana', 0);
		Test.stopTest();

		Assert.areEqual(1, foods.size(), 'Should find one Food item');
		Assert.areEqual(1, searchResults.size(), 'Should find item by search term "Banana"');
	}
}