src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Best Seller</fullName>
                </value>
                <value>
                    <fullName>Exclusive</fullName>
                </value>
                <value>
                    <fullName>Newcoming</fullName>
                </value>
                <value>
                    <fullName>Economical</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Food</fullName>
                </value>
                <value>
                    <fullName>Clothes</fullName>
                </value>
                <value>
                    <fullName>Cars</fullName>
                </value>
                <value>
                    <fullName>Electronics</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ItemsController.cls
public class ItemsController {

	@future(callout=true)
	public static void getFirstThumbnail(Id itemId, String searchTerm) {
		Http h = new Http();
		HttpRequest req = new HttpRequest();
		// I tried to make API call more secure with Named Credential but couldn't do it
		req.setEndpoint('https://api.unsplash.com/search/photos?query=' + searchTerm + '&client_id=6quyStUegacLMNOpn7xTTGJA1RzduRfTkcflmCePp6g');
		req.setMethod('GET');
		HttpResponse res = h.send(req);

		if (res.getStatusCode() == 200) {
			Map<String, Object> root = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
			List<Object> results = (List<Object>) root.get('results');
			if (!results.isEmpty()) {
				Map<String, Object> firstPhoto = (Map<String, Object>) results[0];
				Map<String, Object> urls = (Map<String, Object>) firstPhoto.get('urls');
				String imgUrl =  (String) urls.get('thumb');
				Item__c itemToUpdate = new Item__c(
						Id = itemId,
						Image__c = imgUrl
				);
				update itemToUpdate;
			}
		}
	}

	@AuraEnabled(cacheable=true)
	public static List<Item__c> getAllItems() {
		try {
			return [
					SELECT
							Id,
							Name,
							Description__c,
							Type__c,
							Family__c,
							Image__c
					FROM Item__c
					WITH SECURITY_ENFORCED
					ORDER BY CreatedDate DESC
			];
		} catch (Exception e) {
			throw new AuraHandledException('Error fetching items: ' + e.getMessage());
		}
	}
}