src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account object</description>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrandTotal__c</fullName>
        <label>GrandTotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalItems__c</fullName>
        <label>TotalItems</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>Purchase</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CartControllerTest.cls
@IsTest
private class CartControllerTest {

	@IsTest
	static void testProcessCart() {
		List<CartController.CartItem> items = new List<CartController.CartItem>();

		CartController.CartItem item1 = new CartController.CartItem();
		item1.Id = 'a04d2000002F3KbAAK';
		item1.Name = 'Banana';
		item1.quantity = 2;
		item1.Price = 50.00;
		items.add(item1);

		String accId = '001d200001P0Jf1';
		String accName = 'GenePoint';

		Test.startTest();
		CartController.processCart(items, accId, accName);
		Test.stopTest();

		Purchase__c p = [SELECT Id, Name, ClientId__c FROM Purchase__c LIMIT 1];
		Assert.areEqual('Purchase made by GenePoint', p.Name);
		Assert.areEqual(accId, p.ClientId__c);

		List<PurchaseLine__c> lines = [SELECT Id, Amount__c FROM PurchaseLine__c WHERE PurchaseId__c = :p.Id];
		Assert.areEqual(1, lines.size(), 'Should have created one purchase line');
		Assert.areEqual(2, lines[0].Amount__c);
	}

	@IsTest
	static void testContributeToPurchase() {

		Purchase__c p = new Purchase__c(
				Name = 'Base Purchase',
				TotalItems__c = 10,
				GrandTotal__c = 100.00
		);
		insert p;

		Test.startTest();
		CartController.contributeToPurchase(p.Id, 5, 10.00);
		Test.stopTest();

		Purchase__c updatedP = [SELECT TotalItems__c, GrandTotal__c FROM Purchase__c WHERE Id = :p.Id];
		Assert.areEqual(15, updatedP.TotalItems__c, 'Total items should increment');
		Assert.areEqual(150.00, updatedP.GrandTotal__c, 'Grand total should reflect (5 * 10) addition');
	}
}