src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>ClientId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Account object</description>
        <label>ClientId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Purchases</relationshipLabel>
        <relationshipName>Purchases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrandTotal__c</fullName>
        <label>GrandTotal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalItems__c</fullName>
        <label>TotalItems</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Purchase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ItemId__c</fullName>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>Purchase</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>UnitCost__c</fullName>
        <label>UnitCost</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <label>PurchaseLine Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CartController.cls
public with sharing class CartController {

	public class CartItem {
		@AuraEnabled public String Name {get;set;}
		@AuraEnabled public String Id {get;set;}
		@AuraEnabled public Integer quantity {get;set;}
		@AuraEnabled public Decimal Price {get;set;}
	}

	@AuraEnabled
	public static void processCart(List<CartItem> items, String accountId, String accountName){
		Purchase__c purchase = new Purchase__c();
		purchase.Name = 'Purchase made by ' + accountName;
		purchase.ClientId__c = accountId;
		purchase.GrandTotal__c = 0;
		purchase.TotalItems__c = 0;
		insert purchase;

		for(CartItem item : items){
			PurchaseLine__c purchaseLine = new PurchaseLine__c();
			purchaseLine.ItemId__c = item.Id;
			purchaseLine.PurchaseId__c = purchase.Id;
			purchaseLine.Amount__c = item.quantity;
			purchaseLine.UnitCost__c = item.Price;
			insert purchaseLine;
		}
	}

	@AuraEnabled
	public static void contributeToPurchase(String purchaseId, Decimal amount, Decimal unitCost){
		Purchase__c purchase = [SELECT Id, TotalItems__c, GrandTotal__c
								FROM Purchase__c
								WHERE Id = :purchaseId
								WITH SECURITY_ENFORCED
								LIMIT 1
		];
		purchase.TotalItems__c += amount;
		purchase.GrandTotal__c += (amount * unitCost);
		update purchase;
	}
}